/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingcart;

import java.util.ArrayList;
import java.util.ListIterator;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.text.TableView;

/**
 *
 * @author Tyler
 */
public class UserUI extends javax.swing.JFrame {
    
    CartUI cart = new CartUI();
    DefaultListModel listCart = new DefaultListModel();
    
    String name, type;
    double price = 0;
    int quantity;
    double total = 0;
    double temp = 0;
    
    private ArrayList<Product> productList;
    private ListIterator<Product> listIt;
    int size;
    
    private int countRot = 0;//Dogs
    private int countLab = 0;
    private int countDash = 0;
    private int countBull = 0;
    private int countSia = 0;
    private int countEgypt = 0;
    private int countRag = 0;
    private int countPersian = 0;
    private int countCockatiel = 0;
    private int countScar = 0;
    private int countAfrican = 0;
    private int countSun = 0;
    
    ImageIcon imageRot = new ImageIcon("rottweiler.png");//Dog images
    ImageIcon imageLab = new ImageIcon("Lab.png");
    ImageIcon imageDash = new ImageIcon("Dashound.jpg");
    ImageIcon imageBull = new ImageIcon("Bulldog.png");
    ImageIcon imageSiamese = new ImageIcon("siamese.jpg");//Cat images
    ImageIcon imageEgyptianMau = new ImageIcon("egyptianMau.jpg");
    ImageIcon imageRag = new ImageIcon("ragdoll.jpg");
    ImageIcon imagePersian = new ImageIcon("persian.jpg");
    ImageIcon imageCockatiel = new ImageIcon("Cockatiel.jpg");
    ImageIcon imageScar = new ImageIcon("ScarletMacaw.jpg");
    ImageIcon imageGrey = new ImageIcon("AfricanGreyParrot.jpg");
    ImageIcon imageSun = new ImageIcon("SunConure.png");
    
    /**
     * Creates new form UserUI
     */
    public UserUI() {
        initComponents();
        productList = new ArrayList<>();
        size = 0;
        productList.add(new Product("Rottweiler", "Dog", 10, 100.00));
        productList.add(new Product("Lab", "Dog", 10, 100.00));
        productList.add(new Product("Dashound", "Dog", 10, 100.00));
        productList.add(new Product("Bulldog", "Dog", 10, 100.00));
        productList.add(new Product("Siamese", "Cat", 10, 100.00));
        productList.add(new Product("EgptianMau", "Cat", 10, 100.00));
        productList.add(new Product("RagDoll", "Cat", 10, 100.00));
        productList.add(new Product("Persian", "Cat", 10, 100.00));
        productList.add(new Product("Cockatiel", "Bird", 10, 100.00));
        productList.add(new Product("Scarlet Macaw", "Bird", 10, 100.00));
        productList.add(new Product("African Grey Parrot", "Bird", 10, 100.00));
        productList.add(new Product("Sun Conure", "Bird", 10, 100.00));
        this.setLocationRelativeTo(null);
        setImages();
    }
    
    public UserUI(CartUI c){
        initComponents();
        cart = c;
    }
    
    public void setImages(){
        rottweilerLabel.setText("RottWeiler");//Dogs
        labLabel.setText("Lab");
        dashLabel.setText("Dashound");
        bullLabel.setText("Bulldog");
        siameseLabel.setText("Siamese");//Cats
        egyptLabel.setText("Egyptian Mau");
        ragdollLabel.setText("Ragdoll");
        persianLabel.setText("Persian");
        cockatielLabel.setText("Cockatiel");
        scarletLabel.setText("Scarlet Macaw");
        greyLabel.setText("African Grey Parrot");
        sunLabel.setText("Sun Conure");
    }

    
    private void add(String name, String type, Integer quantity, Double price){//listCart is the model above cartList is the jlist on gui
        cartList.setModel(listCart);
        listCart.addElement(name + ", " + type + "           " + quantity + "          " + price);
    }
    public void addToCart(){
          cart.cartCheckout.addElement(listCart);
    }
    
    public void calculateTotal(){
        total += price;
        totalLabel.setText("" + total);
        cart.totalp = total;
    }
    
    public void removeTotal(){
        total -= price ;
        totalLabel.setText("" + total);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        ordersbtn2 = new javax.swing.JButton();
        messagebtn2 = new javax.swing.JButton();
        accountbtn2 = new javax.swing.JButton();
        cartbtn2 = new javax.swing.JButton();
        doglabel = new javax.swing.JLabel();
        catlabel = new javax.swing.JLabel();
        birdlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rottweilerLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rotPriceCount = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        addRot = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labLabel = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        labCount = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        dashLabel = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        dashCount = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bullLabel = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        bullCount = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        siameseLabel = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        siaCount = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        persianLabel = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        persianCount = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        egyptLabel = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        egyptCount = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ragdollLabel = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        ragCount = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        cockatielLabel = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        cockatielCount = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        scarletLabel = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        scarletCount = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        greyLabel = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        greyCount = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        sunLabel = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        sunCount = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartList = new javax.swing.JList<>();
        checkoutbtn2 = new javax.swing.JButton();
        removebtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));

        titlePanel.setBackground(new java.awt.Color(255, 102, 0));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        title.setText("Welcome To the Online Store!");
        title.setVerifyInputWhenFocusTarget(false);
        titlePanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -30, 270, 120));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));

        ordersbtn2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        ordersbtn2.setText("Orders");
        ordersbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersbtnActionPerformed(evt);
            }
        });

        messagebtn2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        messagebtn2.setText("Messages");
        messagebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebtnActionPerformed(evt);
            }
        });

        accountbtn2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        accountbtn2.setText("Account");
        accountbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountbtnActionPerformed(evt);
            }
        });

        cartbtn2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        cartbtn2.setText("View Cart");
        cartbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartbtn2)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(messagebtn2)
                        .addComponent(accountbtn2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ordersbtn2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messagebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cartbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        doglabel.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        doglabel.setText("Dogs:");

        catlabel.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        catlabel.setText("Cats:");

        birdlabel.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        birdlabel.setText("Birds:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        rottweilerLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        rottweilerLabel.setLabelFor(rottweilerLabel);
        rottweilerLabel.setText("jLabel1");
        jPanel2.add(rottweilerLabel);
        rottweilerLabel.setIcon(imageRot);

        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton1.setText("<");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        rotPriceCount.setText("0");
        jPanel2.add(rotPriceCount);

        jButton13.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton13.setText(">");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);

        addRot.setText("Add");
        addRot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRotActionPerformed(evt);
            }
        });
        jPanel2.add(addRot);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        labLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        labLabel.setText("jLabel1");
        jPanel3.add(labLabel);
        labLabel.setIcon(imageLab);

        jButton14.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton14.setText("<");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);

        labCount.setText("0");
        jPanel3.add(labCount);

        jButton25.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton25.setText(">");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton25);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        dashLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        dashLabel.setText("jLabel2");
        jPanel4.add(dashLabel);
        dashLabel.setIcon(imageDash);

        jButton15.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton15.setText("<");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15);

        dashCount.setText("0");
        jPanel4.add(dashCount);

        jButton26.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton26.setText(">");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton26);

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        bullLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        bullLabel.setText("jLabel3");
        jPanel5.add(bullLabel);
        bullLabel.setIcon(imageBull);

        jButton16.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton16.setText("<");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16);

        bullCount.setText("0");
        jPanel5.add(bullCount);

        jButton27.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton27.setText(">");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton27);

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        siameseLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        siameseLabel.setText("jLabel1");
        jPanel6.add(siameseLabel);
        siameseLabel.setIcon(imageSiamese);

        jButton17.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton17.setText("<");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton17);

        siaCount.setText("0");
        jPanel6.add(siaCount);

        jButton28.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton28.setText(">");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton28);

        jButton12.setText("Add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        persianLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        persianLabel.setText("jLabel2");
        jPanel7.add(persianLabel);
        persianLabel.setIcon(imagePersian);

        jButton18.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton18.setText("<");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton18);

        persianCount.setText("0");
        jPanel7.add(persianCount);

        jButton29.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton29.setText(">");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton29);

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        egyptLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        egyptLabel.setText("jLabel3");
        jPanel8.add(egyptLabel);
        egyptLabel.setIcon(imageEgyptianMau);

        jButton19.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton19.setText("<");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19);

        egyptCount.setText("0");
        jPanel8.add(egyptCount);

        jButton30.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton30.setText(">");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton30);

        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        ragdollLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        ragdollLabel.setText("jLabel4");
        jPanel9.add(ragdollLabel);
        ragdollLabel.setIcon(imageRag);

        jButton20.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton20.setText("<");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton20);

        ragCount.setText("0");
        jPanel9.add(ragCount);

        jButton31.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton31.setText(">");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton31);

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        cockatielLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        cockatielLabel.setText("jLabel5");
        jPanel10.add(cockatielLabel);
        cockatielLabel.setIcon(imageCockatiel);

        jButton24.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton24.setText("<");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton24);

        cockatielCount.setText("0");
        jPanel10.add(cockatielCount);

        jButton35.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton35.setText(">");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton35);

        jButton36.setText("Add");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton36);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        scarletLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        scarletLabel.setText("jLabel6");
        jPanel11.add(scarletLabel);
        scarletLabel.setIcon(imageScar);

        jButton23.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton23.setText("<");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton23);

        scarletCount.setText("0");
        jPanel11.add(scarletCount);

        jButton34.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton34.setText(">");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton34);

        jButton11.setText("Add");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton11);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));

        greyLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        greyLabel.setText("jLabel7");
        jPanel12.add(greyLabel);
        greyLabel.setIcon(imageGrey);

        jButton22.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton22.setText("<");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton22);

        greyCount.setText("0");
        jPanel12.add(greyCount);

        jButton33.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton33.setText(">");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton33);

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton7);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));

        sunLabel.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        sunLabel.setText("jLabel8");
        jPanel14.add(sunLabel);
        sunLabel.setIcon(imageSun);

        jButton21.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton21.setText("<");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton21);

        sunCount.setText("0");
        jPanel14.add(sunCount);

        jButton32.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jButton32.setText(">");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton32);

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton8);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("$5000.00");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setText("$2500.00");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("$2000.00");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setText("$3000.00");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setText("$105.00");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setText("$100.00");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel7.setText("$200.00");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setText("$50.00");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel9.setText("$15.15");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel10.setText("$25.05");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel11.setText("$5.00");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel12.setText("$25.10");

        cartList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cartList);

        checkoutbtn2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        checkoutbtn2.setText("Checkout!");
        checkoutbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });

        removebtn.setText("Remove");
        removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtnActionPerformed(evt);
            }
        });

        jLabel13.setText("Name");

        jLabel14.setText("Type");

        jLabel15.setText("Quantity");

        jLabel17.setText("Price");

        totalLabel.setText("Total");

        jLabel16.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17))
                            .addComponent(checkoutbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(removebtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doglabel)
                            .addComponent(catlabel)
                            .addComponent(birdlabel))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doglabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(catlabel)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(removebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(birdlabel)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkoutbtn2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(totalLabel))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        //Bulldog up
        price += 3000.00;
        countBull++;
        bullCount.setText("" + countBull);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // Sun Conure up
        price += 25.05;
        countSun++;
        sunCount.setText("" + countSun);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        price += 5000.00;
        countRot++;
        rotPriceCount.setText("" + countRot);        // Rottweiler up
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        //Cockatiel up
        price += 15.15;
        countCockatiel++;
        cockatielCount.setText("" + countCockatiel);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // Persian up
        price += 100.00;
        countPersian++;
        persianCount.setText("" + countPersian);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // African Grey Parrot up
        price += 5.00;
        countAfrican++;
        greyCount.setText("" + countAfrican);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        //Dash up
        price += 2000.00;
        countDash++;
        dashCount.setText("" + countDash);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // Ragdoll up
        price += 50.00;
        countRag++;
        ragCount.setText("" + countRag);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        //Siamese up
        price += 105.00;
        countSia++;
        siaCount.setText("" + countSia);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
      price += 2500.00;
        countLab++;
        labCount.setText("" + countLab);   // Lab up
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // Scarlet Macaw up
        price += 25.05;
        countScar++;
        scarletCount.setText("" + countScar);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // Egyptian Mau up
        price += 200.00;
        countEgypt++;
        egyptCount.setText("" + countEgypt);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        dispose();
        cart.setVisible(true);
        addToCart();
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void cartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbtnActionPerformed
        dispose();
        cart.setVisible(true);
        addToCart();
    }//GEN-LAST:event_cartbtnActionPerformed

    private void accountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountbtnActionPerformed
        this.dispose();
        LoginUI frame = new LoginUI();
        frame.setVisible(true);
    }//GEN-LAST:event_accountbtnActionPerformed

    private void messagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebtnActionPerformed
        dispose();
        MessageUI frame = new MessageUI();
        frame.setVisible(true);
    }//GEN-LAST:event_messagebtnActionPerformed

    private void ordersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersbtnActionPerformed
        dispose();
        OrderUI frame = new OrderUI();
        frame.setVisible(true);
    }//GEN-LAST:event_ordersbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        price -= 5000.00;
        countRot--;
        rotPriceCount.setText("" + countRot);//Rottwieler down
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Lab add
        DefaultListModel dlm = new DefaultListModel();
        String s = labCount.getText();
        name = "Labrador";
        type = "Dog";
        quantity = countLab;
        price = Double.parseDouble(s) * 2500.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addRotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRotActionPerformed
        //Rottweiler add
        DefaultListModel dlm = new DefaultListModel();
        
        String s = rotPriceCount.getText();
        name = "Rottweiler";
        type = "Dog";
        quantity = countRot;
        price = Double.parseDouble(s) * 5000.00;
        add(name, type, quantity, price);
        calculateTotal();
        
  
    }//GEN-LAST:event_addRotActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      price -= 2500.00;
        countLab--;
        labCount.setText("" + countLab);  // Lab down
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // Dash down
        price -= 2000.00;
        countDash--;
        dashCount.setText("" + countDash);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        //Bulldog down
        price -= 3000;
        countBull--;
        bullCount.setText("" + countBull);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void removebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebtnActionPerformed
        // Cart remove button
        int index = cartList.getSelectedIndex();
        listCart.remove(index);
        removeTotal();
        
    }//GEN-LAST:event_removebtnActionPerformed

    private void cartListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartListMouseClicked
        // Selection of item in list
        String selected = cartList.getSelectedValue().toString();
    }//GEN-LAST:event_cartListMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Dash add
         DefaultListModel dlm = new DefaultListModel();
        String s = dashCount.getText();
        name = "Dashound";
        type = "Dog";
        quantity = countDash;
        price = Double.parseDouble(s) * 2000.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Bulldog add
         DefaultListModel dlm = new DefaultListModel();
        String s = bullCount.getText();
        name = "Bulldog";
        type = "Dog";
        quantity = countBull;
        price = Double.parseDouble(s) * 3000.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // Siamese down
        price -= 105.00;
        countSia--;
        siaCount.setText("" + countSia);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Siamese add
         DefaultListModel dlm = new DefaultListModel();
        String s = siaCount.getText();
        name = "Siamese";
        type = "Cat";
        quantity = countSia;
        price = Double.parseDouble(s) * 105.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // Persian down
        price -= 100.00;
        countPersian--;
        persianCount.setText("" + countPersian);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //Persian add
         DefaultListModel dlm = new DefaultListModel();
        String s = persianCount.getText();
        name = "Persian";
        type = "Cat";
        quantity = countPersian;
        price = Double.parseDouble(s) * 100.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // Egyptian Mau down
        price -= 200.00;
        countEgypt--;
        egyptCount.setText("" + countEgypt);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Egyptian Mau add
         DefaultListModel dlm = new DefaultListModel();
        String s = egyptCount.getText();
        name = "Egyptian Mau";
        type = "Cat";
        quantity = countEgypt;
        price = Double.parseDouble(s) * 200.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // Ragdoll down
        price -= 50.00;
        countRag--;
        ragCount.setText("" + countRag);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Ragdoll add
         DefaultListModel dlm = new DefaultListModel();
        String s = ragCount.getText();
        name = "Ragdoll";
        type = "Cat";
        quantity = countRag;
        price = Double.parseDouble(s) * 50.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // Cockatiel down
        price -= 15.15;
        countCockatiel--;
        cockatielCount.setText("" + countCockatiel);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // Cockatiel add
        DefaultListModel dlm = new DefaultListModel();
        String s = cockatielCount.getText();
        name = "Cockatiel";
        type = "Bird";
        quantity = countCockatiel;
        price = Double.parseDouble(s) * 15.15;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // Scarlet Macaw down
        price -= 25.05;
        countScar--;
        scarletCount.setText("" + countScar);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Scarlet Macaw  add
        DefaultListModel dlm = new DefaultListModel();
        String s = scarletCount.getText();
        name = "Scarlet Macaw";
        type = "Bird";
        quantity = countScar;
        price = Double.parseDouble(s) * 25.05;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // African Grey Parrot down
        price -= 5.00;
        countAfrican--;
        greyCount.setText("" + countAfrican);
        
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // African Grey Parrot add
        DefaultListModel dlm = new DefaultListModel();
        String s = greyCount.getText();
        name = "African Grey Parrot";
        type = "Bird";
        quantity = countAfrican;
        price = Double.parseDouble(s) * 5.00;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // Sun Conure down
        price -= 25.10;
        countSun--;
        sunCount.setText("" + countSun);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Sun Conure add
        DefaultListModel dlm = new DefaultListModel();
        String s = sunCount.getText();
        name = "Sun Conure";
        type = "Bird";
        quantity = countSun;
        price = Double.parseDouble(s) * 25.05;
        add(name,type, quantity, price);
        calculateTotal();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountbtn2;
    private javax.swing.JButton addRot;
    private javax.swing.JLabel birdlabel;
    private javax.swing.JLabel bullCount;
    private javax.swing.JLabel bullLabel;
    private javax.swing.JList<String> cartList;
    private javax.swing.JButton cartbtn2;
    private javax.swing.JLabel catlabel;
    private javax.swing.JButton checkoutbtn2;
    private javax.swing.JLabel cockatielCount;
    private javax.swing.JLabel cockatielLabel;
    private javax.swing.JLabel dashCount;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JLabel doglabel;
    private javax.swing.JLabel egyptCount;
    private javax.swing.JLabel egyptLabel;
    private javax.swing.JLabel greyCount;
    private javax.swing.JLabel greyLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCount;
    private javax.swing.JLabel labLabel;
    private javax.swing.JButton messagebtn2;
    private javax.swing.JButton ordersbtn2;
    private javax.swing.JLabel persianCount;
    private javax.swing.JLabel persianLabel;
    private javax.swing.JLabel ragCount;
    private javax.swing.JLabel ragdollLabel;
    private javax.swing.JButton removebtn;
    private javax.swing.JLabel rotPriceCount;
    private javax.swing.JLabel rottweilerLabel;
    private javax.swing.JLabel scarletCount;
    private javax.swing.JLabel scarletLabel;
    private javax.swing.JLabel siaCount;
    private javax.swing.JLabel siameseLabel;
    private javax.swing.JLabel sunCount;
    private javax.swing.JLabel sunLabel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

    void setRelativeLocation(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
